packages:
  - 'apps/*'
  - 'packages/*'
  - 'packages/shared/types'
  - 'packages/shared/transformers'
  - 'packages/ui/shadcn'
  - 'tooling/*'
catalog:
  # UI
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  lucide-react: ^0.515.0
  tailwind-merge: ^3.3.1
  tw-animate-css: ^1.3.4
  # Auth
  "@auth/core": 0.37.2
  "@auth/drizzle-adapter": ~1.7.4
  "next-auth": 5.0.0-beta.25
  # GraphQL
  "graphql": ^16.8.1
  "graphql-tag": ^2.12.6
  "mercurius-codegen": ^6.0.1
  "@graphql-codegen/cli": ^5.0.6
  "@graphql-codegen/typescript": ^4.1.6
  "@graphql-codegen/typescript-operations": ^4.6.1
  "@graphql-codegen/typed-document-node": ^5.1.1
  "@graphql-codegen/typescript-react-query": ^6.1.0
  # Fastify
  "@fastify/swagger": ^9.5.1
  "@fastify/swagger-ui": ^5.2.3
  "fastify": ^5.3.2
  "fastify-plugin": ^4.5.1
  "fastify-type-provider-zod": 5.0.1

  # Dev tooling
  "@types/node": "^22.15.30"
  eslint: ^9.23.0
  prettier: ^3.5.3
  rimraf: ^6.0.1
  tailwindcss: ^3.4.15
  tsx: ^4.19.4
  typescript: ^5.8.3
  typescript-eslint: ^8.30.1
  turbo: ^2.5.4
  dotenv: ^16.5.0
  dotenv-cli: ^8.0.0
  tsup: ^8.5.0
  vite: ^6.3.5
  zod: ^3.25.7
catalogs:
  react19:
    react: 19.1.0
    react-dom: 19.1.0
    "@types/react": ^19.1.2
    "@types/react-dom": ^19.1.2